### ISSUE TITLE
undefined method `rootspec=' for #<Pod::Config:0x007fb71c036508>

### ISSUE THREAD

**Issue by siuying** [HipByte/motion-cocoapods#7]
motion-cocoapods not working with cocoapods 0.6.rc1/HEAD

when running rake, following error is shown

```
rake aborted!
undefined method `rootspec=' for #<Pod::Config:0x007fb71c036508>
```
